apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerassignment
  labels:
    app: dockerassignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerassignment
  template:
    metadata:
      labels:
        app: dockerassignment
    spec:
      containers:
      - name: dockerassignment
        image: jatinkumar5346/dockerassignment:latest
        ports:
        - containerPort: 8082